version: '3.8'
services:
  hello-world:
    image: nginx:latest
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy-docker-traefik_routing"
      - "traefik.http.routers.test.rule=Host(`hello-world.test`)"
      - "traefik.http.routers.test.entrypoints=web"
      - "traefik.http.services.test.loadbalancer.server.port=80"
      - "traefik.http.routers.test-https.rule=Host(`hello-world.test`)"
      - "traefik.http.routers.test-https.entrypoints=websecure"
      - "traefik.http.routers.test-https.tls=true"
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    name: reverse-proxy-docker-traefik_routing
    external: true
